services:
  - type: web
    name: worksearchbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: worksearchbot-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.4

databases:
  - name: worksearchbot-db
    database: worksearchbot
    plan: free
    primaryRegion: ohio
    postgreSQLVersion: 15
